FROM jrottenberg/ffmpeg:3-ubuntu

WORKDIR /app

COPY ./entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]

ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install python3 python3-pip libmysqlclient-dev -y

COPY . .
RUN python3 -m pip install -r requirements.txt

WORKDIR /app/videoarchive

CMD ["celery", "-A", "videoarchive", "worker",  "-l", "INFO"]