- name: start mysql container
  community.docker.docker_container:
    name: mysql
    image: "{{ mysql_image }}"
    recreate: true
    volumes:
    - "{{ mysql_volume_name }}:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
    - name: "{{ docker_network_name }}"
    env:
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}}"
    restart_policy: always
